from weapon import Weapon

bow = Weapon("Bow", "Long", "Complex", "Fast", "Mobile", "Utility")
charge_blade = Weapon("Charge Blade", "Short", "Complex", "Hard Hitting", "Defensive", "Damage")
long_sword = Weapon("Long Sword", "Short", "Complex", "Hard Hitting", "Mobile", "Utility")
insect_glaive = Weapon("Insect Glaive", "Short", "Complex", "Fast", "Mobile", "Utility")
dual_blades = Weapon("Dual Blades", "Short", "Simple", "Fast", "Mobile", "Damage")
great_sword = Weapon("Great Sword", "Short", "Simple", "Hard Hitting", "Simple Movement", "Damage")
sword_and_shield = Weapon("Sword and Shield", "Short", "Simple", "Fast", "Mobile", "Utility")
lance = Weapon("Lance", "Short", "Simple", "Fast", "Defensive", "Utility")
gunlance = Weapon("Gunlance", "Short", "Complex", "Hard Hitting", "Defensive", "Damage")
hammer = Weapon("Hammer", "Short", "Simple", "Hard Hitting", "Simple Movement", "Damage")
hunting_horn = Weapon("Hunting Horn", "Short", "Complex", "Hard Hitting", "Simple Movement", "Utility")
switch_axe = Weapon("Switch Axe", "Short", "Complex", "Hard Hitting", "Simple Movement", "Damage")
light_bowgun = Weapon("Light Bowgun", "Long", "Simple", "Fast", "Mobile", "Utility")
heavy_bowgun = Weapon("Heavy  Bowgun", "Long", "Simple", "Hard Hitting", "Simple Movemebt", "Damage")